contact: open.source@ucl.ac.uk

title: "Open Source"
includeleftnav: True
short: "Open Source" # shown as crumbs
navtop: True

defaults:
  - scope: { path: "" }
    values: { layout: default }
  - scope: { path: "news" }
    values: { crumbs: [{ link: "/news/index.html", text: "News" }] }
  - scope: { path: "ospo" }
    values: { crumbs: [{ link: "/ospo/", text: "OSPO" }] }

baseurl: /open-source

remote_theme: UCL-ARC/indigo-jekyll@23-check-ipython-css-exists

plugins:
  - jekyll-remote-theme
  - jekyll-feed

include: # NOTE: This is not a path, but the directories name, wherever they are
  - _static
  - _modules

# collections:
#   phdprojects:
#     output: true
#     #permalink: /:path/index.html
#   rseworkshop:
#     output: true

exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock

markdown: kramdown

kramdown:
  hard_wrap: false
  input: GFM
