accept = [200, 403, 415, 429, 999]
verbose = "info"
no_progress = true
exclude = [
    '(?x).*profiles.ucl.ac.uk.*/thumbnail',   # People may not have a profile image.
    '(?x).*github-readme-stats.vercel.app.*', # Returns 503 for some reason
    '(?x).rdr.ucl.ac.uk/articles/*',          # Article does exist but sometimes returns strange codes: 202, 403...
    '(?x).*127.0.0.1.*',                      # This is a local address
    '(?x).*liveuclac.sharepoint.com/sites/*', # SharePoint pages will need UCL credentials.
    # Several annoying false positives:
    #
    # Some parts of the upstream theme cause errors because they don't prepend https. We don't fix the theme because 
    # it will be updated to the new branding soon. So just suppress all of this for now. Remove when the theme is
    #  updated. All social media links on every theme-rendered page are like this!!
    '(?x).*cdn.ucl.ac.uk/*',
    '(?x).*www.ucl.ac.uk/*',
    '(?x).*shop.ucl.ac.uk',
    '(?x).*www.flickr.com/photos/uclnews',
    '(?x).*www.facebook.com/uclofficial',
    '(?x).*twitter.com/ucl',
    '(?x).*www.instagram.com/ucl',
    '(?x).*www.youtube.com/ucltv',
    '(?x).*soundcloud.com/uclsound',
    # Aaand the favicon and several image paths are broken in the upstream theme, so just ignore these too.
    '(?x).*favicon-152.png',
    '(?x).*assets/images/hero-image-taught-desktop.jpg', # doesn't exist: theme bug
    '(?x).*indigo/images/search-sprite.png',             # doesn't exist: theme bug
    '(?x).*assets/css/owl.video.play.png',
]
